### ISSUE TITLE
0.8.7 version method add in RTree 

### ISSUE THREAD

**Issue by corop** [davidmoten/rtree#100]
What wrong?

`package test;
import com.github.davidmoten.rtree.RTree;
import com.github.davidmoten.rtree.geometry.Geometries;
import com.github.davidmoten.rtree.geometry.Rectangle;

public class Main {
    public static void main(String[] args) {
        RTree<String, Rectangle> rtree = RTree.create();
        Rectangle rectangle1 = Geometries.rectangle(
                10, 10,20, 20
        );
        Rectangle rectangle2 = Geometries.rectangle(
                15, 15,20, 20
        );

        rtree.add("one", rectangle1);
        rtree.add("two", rectangle2);
        System.out.println("rtree = " + rtree.size()); // == 0 expected 2
    }
}`

**Comment by davidmoten** [comment]
It's an immutable data structure. See https://github.com/davidmoten/rtree#add-items-to-the-r-tree.
