### ISSUE TITLE
Rtree can't insert anything

### ISSUE THREAD

**Issue by Fern-Parker** [davidmoten/rtree#127]
import com.github.davidmoten.rtree.*;
import com.github.davidmoten.rtree.geometry.*;
RTree<String,Point> rtree = RTree.create();
rtree.add("1",Geometries.point(1.1,2.2));
rtree.add("2",Geometries.point(2,2));
System.out.println(rtree.isEmpty());

The result is "True", which means  "rtree.add(...)" didn't work. I tried with Line and Rectangle, but I got the same result. Any help will be greatly appreciated!

**Comment by davidmoten** [comment]
See https://github.com/davidmoten/rtree#add-items-to-the-r-tree and the note there that says:

>Important note: being an immutable data structure, calling tree.add(item, geometry) does nothing to tree, it returns a new RTree containing the addition. Make sure you use the result of the add!

**Comment by Fern-Parker** [comment]
您好，您的邮件已收到，我会尽快给您回复
