### ISSUE TITLE
The unit of Circle radius is in meter?

### ISSUE THREAD

**Issue by Fern-Parker** [davidmoten/rtree#128]
The unit of Circle radius is in meter? Any help will be greatly appreciated!

**Comment by davidmoten** [comment]
the unit is whatever unit you are using to express your geometry (it doesn't have to be degrees). 

If it's degrees then you probably want to do a refinement afterwards based on distance from the centre. Look at this example https://github.com/davidmoten/rtree/blob/master/src/test/java/com/github/davidmoten/rtree/LatLongExampleTest.java for a circular search.

**Comment by Fern-Parker** [comment]
I got it. Great thanks for your reply!
