### ISSUE TITLE
Question: how to find overlapping circles?

### ISSUE THREAD

**Issue by tandryukha** [davidmoten/rtree#146]

**Comment by davidmoten** [comment]
So the objects in your dataset have circle regions and you want to find objects with overlapping circles?  How many objects?

Put all the objects in an rtree. Focus on centres of the circles.  Suppose the max size of a circle is M. 

For each object o with radius R:
* ask the rtree for all objects o whose centres are within R + M 
* filter that returned collection to those where there is an overlap with o
* remove o from the rtree 

That do?

**Comment by tandryukha** [comment]
Thanks for the quick response! That is precisely what I was going to do.
But I'm not sure how to deal with geographic coordinates. The goal was to find objects close enough to each other. I was going to use circles for that. But for geo looks like we only have a rectangle, which is similar but a bit less accurate. Is it possible to perform something like that with a geo-circle? I am just not sure which radius I should pick.

`Point airportGeoPoint = Geometries.pointGeographic(longitude, latitude);
        Rectangle closeAirportsRectangle = Geometries.rectangleGeographic();
        Iterable<Entry<Airport, Point>> entries = rtree.search(closeAirportsRectangle).toBlocking().toIterable();`

**Comment by davidmoten** [comment]
This might be helpful

https://github.com/davidmoten/rtree#another-lat-long-example-searching-geo-circles

**Comment by tandryukha** [comment]
Thanks. This is exactly what I was looking for. Using bounded rectangles against R*-tree.
I implemented something similar [here](https://github.com/tandryukha/routing-service/blob/main/src/main/java/com/transporeon/routing/service/RTreeRoutingService.java) in case someone will be interested later. It heavily relies on this R-tree library and bounded rectangle math explained [here](http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates)
