### ISSUE TITLE
Can not find the package "rx.Observable.Operator; rx.Subscriber"

### ISSUE THREAD

**Issue by zhhwGIS** [davidmoten/rtree#18]
In the file - OperatorBoundedPriorityQueue.java, it imports two things: 
``
import rx.Observable.Operator; 
import rx.Subscriber;
``
but i can not find in the code.

**Comment by davidmoten** [comment]
It's in the rx-java dependency in the pom.xml. You haven't used maven?

**Comment by zhhwGIS** [comment]
I do not use maven.  OK， I will go to use it。 thanks！
