### ISSUE TITLE
Is the unit of the parameter radius in CircleDouble. create (x, y, radius) in meters? What other unit is it?

### ISSUE THREAD

**Issue by robben009** [davidmoten/rtree#205]
public static Circle circle(double x, double y, double radius) {
        return CircleDouble.create(x, y, radius);
    }
The specific length unit of the input radius inside is

**Comment by davidmoten** [comment]
There are no units, that's for your domain to decide.

**Comment by robben009** [comment]
Yes, I understand what you mean. I am calculating the range of longitude and latitude for the Earth and now I know how to transmit this radius. Thank you again for your answer.

**Comment by robben009** [comment]
Yes, I understand what you mean. I am calculating the range of longitude and latitude for the Earth and now I know how to transmit this radius. Thank you again for your answer.
