### ISSUE TITLE
RTree.nearest does not return in ascending order of distance

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/rtree#21]
As raised by @virtuald, the use of a Guava ```MinMaxPriorityQueue``` and its iterator under the covers means that there is no guarantee of ascending order of distance. 

The fix will likely be to not use the iterator to emit the elements but rather poll in a loop.

**Comment by davidmoten** [comment]
I'll do the release to Maven Central in a few hours time.

**Comment by davidmoten** [comment]
Fix released in 0.5.8 @virtuald

**Comment by virtuald** [comment]
Thanks!
