### ISSUE TITLE
Geometry type classes are final

### ISSUE THREAD

**Issue by chhh** [davidmoten/rtree#25]
It's not a real issue, but the problem is that class names like Rectangle and Point collide with other class names, e.g. `java.awt.Rectangle`, so I'm stuck using full class names. Would that be possible to remove the `final` modifier from those?

**Comment by davidmoten** [comment]
I'm reluctant to support inheritance in the API. If the name collision annoys you enough you could make your own class `MyPoint` and use composition for the implementation.

**Comment by chhh** [comment]
Ok, got it, thanks!
