### ISSUE TITLE
Possible issue with SplitterRStar

### ISSUE THREAD

**Issue by i-sinister** [davidmoten/rtree#26]
I've been checking implementation and found following issue with  method SplitterRStar
.getPairs - it is expected to generate possible partitionings of list of nodes where each partition has at least minSize items. However in the implementation 'last' partitioning is not checked - for example when there are 9 items in the list, and minSize is 3, possible partitionings should be: 3-6,4-5,5-4,6-3; but current implementation does not generate last one.

I'm not sure if it is a bug or expected behavior as I havent read original paper and I 'like' more picture generated by the original algorithm (without 'fixing this bug'). However if it is a bug then for-loop in SplitterRStar.getPairs should be changed to
```java
for (int i = minSize; i < list.size() - minSize + 1; i++) 
```

**Comment by davidmoten** [comment]
Thanks for looking at the implementation to that detail! I'll have a look
at it soon.

**Comment by davidmoten** [comment]
Great catch, thanks a lot. I've committed the fix with a unit test and I'll put up a release shortly with that fix. Just for general awareness for people that see this issue, the problem has no effect on the correctness of the `RTree` implementations but it did mean that the R-Star version diverged slightly from the definition and was in theory not as as good as it can be.

**Comment by davidmoten** [comment]
0.6.4 is released with the fix
