### ISSUE TITLE
Longitude -180 normalized to 180

### ISSUE THREAD

**Issue by dkadams** [davidmoten/rtree#28]
I encountered a problem using the R-Tree and the root cause appeared to be that `Geometries.normalizeLongitude` was adjusting -180 to 180. 

That seems to contradict the [documentation](https://github.com/davidmoten/rtree#geospatial-geometries-lats-and-longs), which indicates that longitudes are normalized to [-180, 180).

Thanks!

**Comment by davidmoten** [comment]
Thanks for the report. It's now fixed in master and I'll release to Maven Central in a couple of hours.

**Comment by davidmoten** [comment]
Fix is in release 0.6.8 on Maven Central
