### ISSUE TITLE
Util.mbr() issues with negative numbers such as negative longitudes

### ISSUE THREAD

**Issue by dsmoses** [davidmoten/rtree#34]
Float.MIN_VALUE is "the smallest positive nonzero value of type float". This causes issues with negative values. In particular, I noticed in my tests that a negative longitude value was resulting in a maxX2 (and resulting Rectangle x2) value of 1.4E-45.

Please consider changing from:

float maxX2 = Float.MIN_VALUE;
float maxY2 = Float.MIN_VALUE;

to:

float maxX2 = -Float.MAX_VALUE;
float maxY2 = -Float.MAX_VALUE;

**Comment by davidmoten** [comment]
Thanks for this report, excuse my tardiness in addressing it! You are quite right, I'll knock up tests and fix and release very soon.

**Comment by davidmoten** [comment]
fix released to Maven Central as 0.7.1
