### ISSUE TITLE
Retrieving the root mbr of the tree

### ISSUE THREAD

**Issue by HassanElsherbini** [davidmoten/rtree#35]
thank you very much for this great implementation, I was wondering if there is a way I can retrieve the root node or basically the minimum bounding rectangle that covers all the points in the tree.

**Comment by davidmoten** [comment]
your welcome, glad it's useful for you. I don't think that information is available at the moment but I don't see a problem in adding it. I'll have a look in the next few days.

**Comment by davidmoten** [comment]
This addition is released now to Maven Central as 0.7

**Comment by HassanElsherbini** [comment]
Thank you very much
