### ISSUE TITLE
Benchmark fails with Cannot parse argument '-i' of option ['f']

### ISSUE THREAD

**Issue by Crystark** [davidmoten/rtree#36]
Just trying to launch benchmarks with `mvn clean install -Pbenchmark` and I get the following error:

```
[INFO] --- exec-maven-plugin:1.3.2:exec (run-benchmarks) @ rtree ---
Error parsing command line:
 Cannot parse argument '-i' of option ['f']
```

I'm using maven 3.3.9.
Thanks :)

**Comment by davidmoten** [comment]
Thanks for that. An upgrade of jmh should have been accompanied with a removal of the -f flag. I've done that and upgraded jmh from 1.11.1 to 1.11.2.
