### ISSUE TITLE
Tree hangs when finding the nearest 

### ISSUE THREAD

**Issue by x2b** [davidmoten/rtree#38]
I have the following example:

    import com.github.davidmoten.rtree.RTree;
    import com.github.davidmoten.rtree.geometry.Geometries;
    import com.github.davidmoten.rtree.geometry.Line;

    public class TreeExample {

        public static void main(String[] args) {

            RTree<String, Line> tree = RTree.star().create();

            for(int i = 0; i < 5;++i) {
                tree = tree.add(String.format("Hello %d", i), Geometries.line(-i, -i, 5 + i, i));
            }

            System.out.println(tree.nearest(Geometries.point(2, 0.4), Double.MAX_VALUE, 1)
                    .toBlocking().single().value());

        }
    }

Unfortunately the program hangs and I never get any output. Any ideas what is causing this?

I am using the following version:

    <dependency>
      <groupId>com.github.davidmoten</groupId>
      <artifactId>rtree</artifactId>
      <version>0.7.2</version>
    </dependency>
    <dependency>
      <groupId>com.vividsolutions</groupId>
      <artifactId>jts-core</artifactId>
      <version>1.14.0</version>
    </dependency>

**Comment by davidmoten** [comment]
Thanks I'll have a look soon

**Comment by davidmoten** [comment]
Thank you very much for the report. It was a bug with `OperatorBoundedPriorityQueue` that needed to request `Long.MAX_VALUE` of upstream.

I've just released 0.7.4 with the fix to Maven Central, should be available there in about 10mins.

**Comment by x2b** [comment]
Thank you for the fix :)
