### ISSUE TITLE
Thanks for the awesome library!

### ISSUE THREAD

**Issue by marsxu1984** [davidmoten/rtree#43]
**I write this issue not for reporting bug.**
I'm using davidmoten/rtree for big,large map world for mmo SLG, AOI (area of interect) is very important feature for this kind of game.
I find a lot of r-tree libs for java, davidmoten is the best, not one of.
Most of all, davidmoten/rtree is very easy to make a dynamical rtree, every entity in the game world, could change their position if they want.
Thanks davidmoten.

**Comment by davidmoten** [comment]
Very kind of you, it's pleasing to have appreciative users!
I won't be in a rush to close this issue!
