### ISSUE TITLE
Rtree Entries 

### ISSUE THREAD

**Issue by aminaHit** [davidmoten/rtree#46]
is there any solution how to add entries with this manner 
<id,String, Rtree> like (1,david,(-1,3))

**Comment by davidmoten** [comment]
I don't understand the question. Do you mean an `RTree` where the entry value (not the geometry) is an arbitrary type? In that case sure you just create an `RTree<Object, Geometry>`.

**Comment by aminaHit** [comment]
I mean that the entry value has two entries like RTree<Object1, Object2, Geometry> 
I will need to work with Object1 which is an ID of the point
 Object2 is the name of the point 

can we add this ?

**Comment by davidmoten** [comment]
Just create a class to wrap the id and the name and objects of that class will be the value in the RTree.

**Comment by aminaHit** [comment]
Can you give me an example ? 

by the way, thanks a lot for your help is very useful

**Comment by davidmoten** [comment]
Ok let's take this:

` (1,david,(-1,3))`

I assume the `(-1,3)` is the position part.

```java
public static class Thing {
    final int number;
    final String name;

    public Thing(int number, String name) {
        this.number = number; 
        this.name = name;
    }
}

RTree<Thing, Point> tree = RTree.create();
tree = tree.add(new Thing(1, "david"), Geometries.point(-1, 3));
```

**Comment by aminaHit** [comment]
It's very useful, Thank you so much @davidmoten
