### ISSUE TITLE
Deserialization bug

### ISSUE THREAD

**Issue by eadwright** [davidmoten/rtree#50]
Using 0.8-RC7, I've seen the following problem when trying to deserialize a tree:

```
Caused by: java.lang.RuntimeException: unexpected
	at com.github.davidmoten.rtree.fbs.SerializerFlatBuffers.readFully(SerializerFlatBuffers.java:165)
	at com.github.davidmoten.rtree.fbs.SerializerFlatBuffers.read(SerializerFlatBuffers.java:123)
```

The error occurs here:

```
    @VisibleForTesting
    static byte[] readFully(InputStream is, int numBytes) throws IOException {
        byte[] b = new byte[numBytes];
        int n = is.read(b);
        if (n != numBytes)
            throw new RuntimeException("unexpected");
        return b;
    }
```

I believe the contract of InputStream.read(byte[]) does not always do full reads, there should be some form of loop here to retry. I've seen such errors before.

Do let me know if I'm missing something.

**Comment by eadwright** [comment]
I should add my tree is large, approx 1GB. I guess I'm correct in assuming things can't work above 2GB either?

**Comment by eadwright** [comment]
Tried overriding the SerializerFlatBuffers class locally just to test a fix, this works and solves my problem:

```
    @VisibleForTesting
    static byte[] readFully(InputStream is, int numBytes) throws IOException {
        byte[] b = new byte[numBytes];

        int count = 0;
        do {
            int n = is.read(b, count, numBytes - count);
            if(n > 0)
                count += n;
            else
                throw new RuntimeException("unexpected");
        } while(count < numBytes);

        return b;
    }
```

**Comment by davidmoten** [comment]
Thanks very much @eadwright for the report and for the fix! I'll knock up the appropriate unit test and release when done.

**Comment by davidmoten** [comment]
0.8-RC8 released to Maven Central, thank you very much for report and fix!

**Comment by eadwright** [comment]
:) You're welcome, thanks for such a rapid response
