### ISSUE TITLE
Suggestion on how does Immutability of this Implementation suitable for writing Concurrenct, Thread Safe Code

### ISSUE THREAD

**Issue by ksaurab** [davidmoten/rtree#51]
I was looking into RTree.add(), RTree.delete() and I am wondering if I can perform these operations using multiple threads without worrying about any synchronization construct at my end. I assume that it will not return me correct tree because if I add 2 entries to the RTree parallely, once both the threads complete, the resulting RTree wont have both entries, similarly for the Delete Operation.

Please clarify if my understanding is wrong.

If I talk about search operation, it is not going to mutate the RTree's state, so immutability has no role here. These questions are arising as I might have to create the RTree multiple times in the same process with too much of data and hence will have to perform add operation in multiple threads.

Regards
Saurabh

**Comment by davidmoten** [comment]
Yep for adding/deleting you'll have to do your own synchronization as you have to assign the result of add/delete to a variable. You could use a `synchronized` block or use an `AtomicReference<RTree>` and update it in a CAS loop.
