### ISSUE TITLE
why can't we find polyline,polygon

### ISSUE THREAD

**Issue by liyihongcug** [davidmoten/rtree#57]
why can't we find polyline,polygon in geometries

**Comment by davidmoten** [comment]
You can extend RTree with your own geometries if you wish (use geotools for instance). See README for discussion. Also happy to look at a PR but bear in mind that when you introduce a new geometry to the RTree core you have to implement intersection and distance functions with every other geometry so its a bit of work. If you implement it yourself in your own project then you only have to support intersection and distance functions with the subset of geometries you use.

**Comment by liyihongcug** [comment]
thanks。 I solved it .
please review it   https://github.com/davidmoten/rtree-3d/issues/1
