### ISSUE TITLE
why need it so long time to create R tree?

### ISSUE THREAD

**Issue by liyihongcug** [davidmoten/rtree#58]
code are in rtree/src/test/java/com/github/davidmoten/rtree/GreekEarthquakes.java

    public static void main(String[] args) throws InterruptedException {
        RTree<Object, Point> tree = RTree.star().create();
        tree = tree.add(entries()).last().toBlocking().single();
        System.gc();
        Thread.sleep(10000000);  //？？？   I don't bear it
        System.out.println(tree.size());
    }

10000000 > 2 hours.
Only 38377 rows    == requires so long time??

          I don't understand.

**Comment by davidmoten** [comment]
Just get rid of the sleep, that's hanging around from an async test.

**Comment by davidmoten** [comment]
no, that's right I was checking heap usage...
