### ISSUE TITLE
Point.contains() method is always true

### ISSUE THREAD

**Issue by KoheiKanagu** [davidmoten/rtree#60]
Hello davidmoten

I think this **contains()** is always true.
So, I think there is need change to this.x and this.y.

```
    @Override
    public boolean contains(double x, double y) {
        return x == x && y == y;
    }
```

in here
https://github.com/davidmoten/rtree/blob/master/src/main/java/com/github/davidmoten/rtree/geometry/Point.java#L121

Thanks.

**Comment by davidmoten** [comment]
Thanks for the report! Fixing now.

**Comment by davidmoten** [comment]
0.8-RC10 released to Maven Central with the fix, thanks again.
