### ISSUE TITLE
asString() print nothing

### ISSUE THREAD

**Issue by tongjiyiming** [davidmoten/rtree#64]
I use 0.8-RC9 release. Here is a simple test code:

`public class ProcessFilesClient {
	public static void main( String[] args ) {
		RTree<String, Geometry> tree = RTree.minChildren(2).maxChildren(4).star().create();
		System.out.println(tree.toString());
		
		tree.add("a", Geometries.point(2, 3));
		tree.add("b", Geometries.point(3, 8));
		tree.add("c", Geometries.point(3, 5));
		tree.add("f", Geometries.point(9, 17));
		tree.add("g", Geometries.point(87, 56));
		tree.add("j", Geometries.point(86, 54));
		tree.add("u", Geometries.point(89, 59));
		tree.add("p", Geometries.point(81, 50));
		System.out.println("str: " + tree.asString());

	}
}`

but I print out:

'com.github.davidmoten.rtree.RTree@77459877
str: '

What is the problem? is there any dependencies I did not have?

**Comment by tongjiyiming** [comment]
No problem. I just found I should use tree = tree.add(), since it is a immutable instance.

**Comment by davidmoten** [comment]
Cool, glad you sorted it.
