### ISSUE TITLE
Is Android supported?

### ISSUE THREAD

**Issue by splangi** [davidmoten/rtree#73]
As java.awt.* libraries are often used in the project, then this means that Android is not supported. Although it was never mentioned that Android is supported, then it would be nice if a small remark would be added to the readme.md about not supporting Android. Implemented it in my project and just found out that it will not work.

**Comment by davidmoten** [comment]
I don't believe this is the case, you just need the appropriate ProGuard rules to exclude. I'll check awt usage now.

**Comment by davidmoten** [comment]
These files reference awt:

```
./src/main/java/com/github/davidmoten/rtree/Visualizer.java
./src/main/java/com/github/davidmoten/rtree/ImageSaver.java
./src/main/java/com/github/davidmoten/rtree/geometry/Line.java
```
I expected the `Visualizer` and `ImageSaver` which would be excluded in ProGuard rules but `Line` should not have references. I'll fix and release.

Would you be able to contribute a tested ProGuard rules file that excludes `Visualizer` and `ImageSaver`?

**Comment by davidmoten** [comment]
0.8.0.3 has been released to Maven Central and contains a reworked `Line` class that doesn't depend on `java.awt` (I ported the required methods from `java.awt.geom.Line2D`).

**Comment by davidmoten** [comment]
To clarify, `Visualizer` and `ImageSaver` are not required for normal r-tree usage so can be excluded. I could push those classes into a another module (like *rtree-visualizer*) but I'm not sure how much trouble the ProGuard side of things is as I'm not doing Android dev. Input on this welcome!

**Comment by splangi** [comment]
Porting Line2D from awt does not help much because of the JTS library. JTS uses awt quite heavily. Don't know how hard it would be to port the functions from JTS to this project. 

Note: Originally I was trying to use rtree with the line class and included JTS. Thats why I thought it was hopeless when i searched for java.awt dependancies in the libraries (which included both rtree and JTS dependancies).

About writing the proguard rules, then I can write them. But isn't Proguard used in non-Android projects as well? Also should the Line class be excluded (And then it should be marked that Android does not support the Line geometry)?

**Comment by davidmoten** [comment]
Ah JTS is the problem. The `Line` class is the only place that uses JTS so if you don't use `Line` then you can exclude the JTS dependency. 

If you do want to use the `Line` class on Android then we'll have to implement the method that determines if the line intersects a rectangle locally. Not too hard to do I'm sure, I'll have a look at it.

**Comment by davidmoten** [comment]
0.8.0.4 has been released to Maven Central and the JTS dependency has been removed. 

I copied the rectangle intersect with line code from Rectangle2D but had to supplement it so that intersections with the border were detected also. New code if you wish to inspect is in `RectangleUtil`.

I also took the liberty of changing the issue title because it was a bit strong given that I now support Android fully.

@splangi Please try it out, and I'd love to take you up on the ProGuard rules to leave out `Visualizer` and `ImageSaver`. Paste them here if you like or submit a PR.

**Comment by splangi** [comment]
Tried to compile a build with proguard. The following problems popped up
[Long list of warnings](https://pastebin.com/fgREx4Pv)

The issue goes further than just AWT.

The following proguard rules makes it ignore the warnings and it compiles:

`-dontwarn com.github.davidmoten.rtree.Visualizer
-dontwarn com.github.davidmoten.rtree.fbs.**
-dontwarn com.github.davidmoten.rtree.kryo.**
-dontwarn com.github.davidmoten.rtree.Visualizer
-dontwarn com.github.davidmoten.rtree.Serializers**
-dontwarn com.github.davidmoten.rtree.ImageSaver**`

Although this does not mean, that the non-supported classes couldn't be used during development. Proguard is a tool for after build optimizing, shrinking etc. 
[Proguard manual](https://www.guardsquare.com/en/proguard/manual/introduction)

The exclusion of classes should be done by Gradle. I looked into it and there is no obvious non-hack method to exclude classes from the library. Maybe I did not look hard enough.

Looking forward to your input @davidmoten

**Comment by davidmoten** [comment]
Looks like ProGuard is unaware of the project dependencies (and it needs to
be). You'll need to configure it to be aware of them I suppose.

**Comment by BaptisteMahe** [comment]
Hello,

Regarding Android support, I found out that the `RectangleUtil.rectangleIntersectsLine` method still relies on `java.awt.geom.Line2D`. Cf [RectangleUtil.java](https://github.com/davidmoten/rtree/blob/master/src/main/java/com/github/davidmoten/rtree/internal/RectangleUtil.java#L46)

This causes Android projects to raise `java.lang.NoClassDefFoundError` exception when trying to delete entries inside a RTree with Line entries.

I checked the code and it looks like you already implemented your own `_rectangleIntersectsLine` method but still fallback to `Line2D.Double.linesIntersect`. I tried to remove this and ran the tests and it looked good to me but I might be missing.

Should I open a new issue about this ?

**Comment by davidmoten** [comment]
ah, thanks. Sounds like we should do something about that. I'll fix.

**Comment by davidmoten** [comment]
[0.12](https://github.com/davidmoten/rtree/releases/tag/0.12) is released to Maven Central with the fix, thanks for the report!

**Comment by BaptisteMahe** [comment]
Thank you for the fix and the deployment so fast !

I will try 0.12 today.

**Comment by BaptisteMahe** [comment]
I tested the 0.12 release and the issue is gone, thank you very much!
