### ISSUE TITLE
What am i missinng

### ISSUE THREAD

**Issue by boyravikumar** [davidmoten/rtree#82]
RTree<String, Geometry> tree = RTree.create();

        tree.add("hello", Geometries.rectangle(0, 0, 2, 2));
        tree.add("hello", Geometries.rectangle(0, 0, 20, 20));

        List<Entry<String, Geometry>> results =
                tree.search(Geometries.rectangle(0,0,10001,10001)).toList().toBlocking().single();
        
       // results = tree.entries().toList().toBlocking().single();
      //by enabling above statement as well i am not getting anything. What am i missing.

        for (Entry<String,Geometry> result: results) {
            System.out.println(result.value());
        }

**Comment by boyravikumar** [comment]
Don't consider it as spam. This is the only place i can ask for questions right now.

**Comment by davidmoten** [comment]
Tree is immutable so you need to assign it. For example tree = tree.add... See README.md.

**Comment by boyravikumar** [comment]
Yeah.. I totally missed it. Thanks for the response!!
