### ISSUE TITLE
Mutable version

### ISSUE THREAD

**Issue by mpires** [davidmoten/rtree#86]
Hi,

Is there a plan to have a mutable version of the `RTree` for cases where thread safety is externally guaranteed?

**Comment by davidmoten** [comment]
No, no plan at the moment. Out of interest what's your use case? You want better perf (reduced allocations) for a load or updates and are prepared to make reads and writes non-concurrent?

**Comment by mpires** [comment]
Since I'm performing updates on the structure sequentially with an actor-based approach, indeed it'd be preferable to reduce the allocations.
For now your implementation totally fits my use case of some basic spatial queries. Good stuff.

**Comment by davidmoten** [comment]
What about reads? You want to make reads wait on writes and vice versa?

**Comment by mpires** [comment]
At least for now, yes, I'm doing operations on the structure in an ordered fashion

**Comment by davidmoten** [comment]
ok thanks, no plans for mutable r-tree. Would be a complete rewrite and would not make sense to combine with streaming (RxJava) as was done. I quite enjoy knocking new things up but don't have a compelling use case for this personally so may leave it for the moment.

**Comment by mpires** [comment]
Of course, makes perfect sense. For so many cases, the immutability you offer is highly desirable.
